FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Polls API

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            
            
## IDAP :: Customer Dashboard - Summary [/subscriber-statuses]

### List All Subscribers Statuses [GET]

+ Response 200 (application/json)

        [
              {
                "idap_module": "Subscriber Statuses",
                "updated_at": "2017-03-14T08:40:51.620Z"
              },
              {
                "status":
                    {
                        "activated": 120,
                        "provisioned": 150,
                        "suspended": 30
                    }                
              }       
        ]

## IDAP :: Summary - Online Subscribers [/online-subscribers-no-filter]

### Online Subscribers  [GET]

+ Response 200 (application/json)

        [
              {
                "idap_module": "Online Subscribers No Filter",
                "updated_at": "2017-03-14T08:40:51.620Z"
              },
              {
                "target": "carbon.agents.subscribers.online",
                "datapoints": [
                    [
                        100,
                        1521117120
                    ],
                    [
                        150,
                        1521117180
                    ]
                ]
              }       
        ]
        
## IDAP :: Summary - F5 CPU Usage [/f5-cpu-usage]

### F5 CPU Usage  [GET]

+ Response 200 (application/json)

        [
              {
                "idap_module": "F5 CPU Usage",
                "updated_at": "2017-03-14T08:40:51.620Z"
              },
              {
                "target": "carbon.agents.server-1.cpuUsage",
                "datapoints": [
                  [
                    0.20639360452556796,
                    1521117120
                  ],
                  [
                    0.020000277999927395,
                    1521117180
                  ]
                ]
              },
              {
                "target": "carbon.agents.server-2.cpuUsage",
                "datapoints": [
                  [
                    0.026665320040574116,
                    1521088920
                  ],
                  [
                    0.02666483255922161,
                    1521088980
                  ]
                ]
              }            
        ]
        
## IDAP :: Summary - Success Vs Failure Calls [/success-failure-calls]

### Success Vs Failure Calls  [GET]

+ Response 200 (application/json)

        [
          {
            "idap_module": "Success Vs Failure Calls",
            "updated_at": "2017-03-14T08:40:51.620Z"
          },
          {
            "target": "elasticsearch.<index_name>",
            "aggregations": {
              "success_stats": {
                "bg_call": {
                  "count": 2,
                  "percentage": 17
                },
                "adhc_call": {
                  "count": 30,
                  "percentage": 88
                },
                "grp_call": {
                  "count": 50,
                  "percentage": 91
                },
                "pvt_call": {
                  "count": 162,
                  "percentage": 98
                },
                "all": {
                  "count": 80,
                  "percentage": 88
                }
              },
              "failure_stats": {
                "bg_call": {
                  "count": 10,
                  "percentage": 83
                },
                "adhc_call": {
                  "count": 4,
                  "percentage": 12
                },
                "grp_call": {
                  "count": 5,
                  "percentage": 9
                },
                "pvt_call": {
                  "count": 3,
                  "percentage": 88
                },
                "all": {
                  "count": 22,
                  "percentage": 2
                }
              }
            }
          }
        ]
        
## IDAP :: Subscribers - Manufacturer Count [/manufacturer-count]

### Manufacturer Count  [GET]

+ Response 200 (application/json)

        [
          {
            "idap_module": "Manufacturer Count",
            "updated_at": "2017-03-14T08:40:51.620Z"
          },
          {
            "target": "elasticsearch.<index_name>",
            "aggregations": {
              "manufacturer_count": {
                "sonim": {
                  "count": 50
                },
                "samsung": {
                  "count": 20
                },
                "kyocera": {
                  "count": 10
                },
                "apple": {
                  "count": 15
                },
                "blackberry": {
                  "count": 5
                }
              }
            }
          }
        ]
        
## IDAP :: Subscribers - Device OS Count [/device-os-count]

### Device OS Count  [GET]

+ Response 200 (application/json)

        [
          {
            "idap_module": "Device OS Count",
            "updated_at": "2017-03-14T08:40:51.620Z"
          },
          {
            "target": "elasticsearch.<index_name>",
            "aggregations": {
              "device_os_count": {
                "android": {
                  "count": 70
                },
                "ios": {
                  "count": 30
                },
                "windows": {
                  "count": 20
                },
                "unknown": {
                  "count": 5
                },
                "blackberry": {
                  "count": 25
                }
               }
            }
          }
        ]
        
## IDAP :: Subscribers - Device Model Count [/device-model-count]

### Device Model Count  [GET]

+ Response 200 (application/json)

        [
          {
            "idap_module": "Device Model Count",
            "updated_at": "2017-03-14T08:40:51.620Z"
          },
          {
            "target": "elasticsearch.<index_name>",
            "aggregations": {
              "device_model_count": {
                "sonim xps": {
                  "count": 50
                },
                "kyocera duraforce": {
                  "count": 20
                },
                "samsung galaxy rugby pro": {
                  "count": 10
                },
                "sonim xps560 bolt": {
                  "count": 15
                },
                "kyocera dura xe": {
                  "count": 5
                },
                "sonim xp1520 bolt sl": {
                  "count": 5
                }
               }
            }
          }
        ]